version: '3'

services:
  ui:
    hostname: ui
    image: iconix/reactml
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./config-overrides.js:/app/config-overrides.js

volumes:
  .: